version: '3'

services:
  mariadb:
    image: mariadb:${TAG}
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT: ${MYSQL_ROOT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./.env
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    image: wordpress:${TAG}
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      # args:
    #     MYSQL_HOST: ${MYSQL_HOST}
    #     MYSQL_PORT: ${MYSQL_PORT}
    #     MYSQL_ROOT: ${MYSQL_ROOT}
    #     MYSQL_PORT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #     MYSQL_DATABASE: ${MYSQL_DATABASE}
    #     MYSQL_USER: ${MYSQL_USER}
    #     DOMAIN_NAME: ${DOMAIN_NAME}
    #     WP_TITLE: ${WP_TITLE}
    #     WP_ADMIN: ${WP_ADMIN}
    #     WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    #     WP_ADMIN_PW: ${WP_ADMIN_PW}
    #     WP_PORT: ${WP_PORT}
    #     WP_USER: ${WP_USER}
    #     WP_USER_EMAIL: ${WP_USER_EMAIL}
    #     WP_USER_PW: ${WP_USER_PW}
    env_file:
      - ./.env
    expose:
      - "9000"
    restart: unless-stopped
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_net

  nginx:
    image:  nginx:${TAG}
    container_name: nginx
    env_file:
      - ./.env
    build:
      context: ./requirements/nginx
      args:
        CERTS: ${CERTS}
        KEYS: ${KEYS}
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_net

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/data/wordpress
      #fix it in virtualBox!!
      # device: /home/soum/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/data/mariadb
      #fix it in virtualBox!!
      # device: /home/soum/data/mariadb

networks:
  inception_net:
    driver: bridge
