version: '3'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/docker/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/docker/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
