version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
      # context: .
      # dockerfile: ./requirements/mariadb/Dockerfile
    restart: unless-stopped
    ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
      # context: .
      # dockerfile: ./requirements/wordpress/Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ~/wordpress/:/var/www/soum/html
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
      # context: .
      # dockerfile: ./requirements/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ~/wordpress:/var/www/soum/html
    depends_on:
      - wordpress
