version: '3'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    volumes:
      - wp:/var/www/
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/
    depends_on:
      - wordpress
