version: '3'

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/soum/data/mariadb

services:
  mariadb:
    image: mariadb:${TAG}
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT: ${MYSQL_ROOT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:${TAG}
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - mariadb

  nginx:
    image:  nginx:${TAG}
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        CERTS: ${CERTS}
        KEYS: ${KEYS}
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
